### ISSUE TITLE
Login Submit Button not Correctly Aligned

### ISSUE THREAD

**Issue by torinberger** [MHSCodeGithub/portable-octopus#1] opened 2018-08-03 22:28 UTC
browser: chrome
os: osx

The submit button is in the form edge and the text inside is not center aligned.

**Comment by torinberger** [comment] 2018-08-03 22:41
also login/register error messages need to be handled and placed correctly.

**Comment by Kowstof** [comment] 2018-08-11 14:43
Fixed by adding a normalize stylesheet. Probably caused by the way Chrome renders margins.

**Closed as completed by Kowstof** 2018-08-11 14:43 UTC
Labels: bug
